### Créer un enfant
POST http://localhost:8081/children?username=admin
Content-Type: application/json

{
  "nom": "Ali",
  "dateNaissance": "2015-01-10"
}

### Lister les enfants du partenaire
GET http://localhost:8081/children?username=admin

### Récupérer un enfant par ID
GET http://localhost:8081/children/1

### Mettre à jour l’enfant
PUT http://localhost:8081/children/1
Content-Type: application/json

{
  "nom": "Ali Modifie",
  "dateNaissance": "2015-01-10",
  "statut": "actif"
}

### Supprimer l’enfant
DELETE http://localhost:8081/children/1
